weather={
	'thunderstorm with light rain':{'id':200, 'icon':'11d.png'},
	'thunderstorm with rain':{'id':201, 'icon':'11d.png'},
	'thunderstorm with heavy rain':{'id':202, 'icon':'11d.png'},
	'light thunderstorm':{'id':210, 'icon':'11d.png'},
	'thunderstorm':{'id':211, 'icon':'11d.png'},
	'heavy thunderstorm':{'id':212, 'icon':'11d.png'},
	'ragged thunderstorm':{'id':221, 'icon':'11d.png'},
	'thunderstorm with light drizzle':{'id':230, 'icon':'11d.png'},
	'thunderstorm with drizzle':{'id':231, 'icon':'11d.png'},
	'thunderstorm with heavy drizzle':{'id':232, 'icon':'11d.png'},
	'light intensity drizzle':{'id':300, 'icon':'09d.png'},
	'drizzle':{'id':301, 'icon':'09d.png'},
	'heavy intensity drizzle':{'id':302, 'icon':'09d.png'},
	'light intensity drizzle rain':{'id':310, 'icon':'09d.png'},
	'drizzle rain':{'id':311, 'icon':'09d.png'},
	'heavy intensity drizzle rain':{'id':312, 'icon':'09d.png'},
	'shower rain and drizzle':{'id':313, 'icon':'09d.png'},
	'heavy shower rain and drizzle':{'id':314, 'icon':'09d.png'},
	'shower drizzle':{'id':321, 'icon':'09d.png'},
	'light rain':{'id':500, 'icon':'10d.png'},
	'moderate rain':{'id':501, 'icon':'10d.png'},
	'heavy intensity rain':{'id':502, 'icon':'10d.png'},
	'very heavy rain':{'id':503, 'icon':'10d.png'},
	'extreme rain':{'id':504, 'icon':'10d.png'},
	'freezing rain':{'id':511, 'icon':'13d.png'},
	'light intensity shower rain':{'id':520, 'icon':'09d.png'},
	'shower rain':{'id':521, 'icon':'09d.png'},
	'heavy intensity shower rain':{'id':522, 'icon':'09d.png'},
	'ragged shower rain':{'id':531, 'icon':'09d.png'},
	'light snow':{'id':600, 'icon':'13d.png'},
	'snow':{'id':601, 'icon':'13d.png'},
	'heavy snow':{'id':602, 'icon':'13d.png'},
	'sleet':{'id':611, 'icon':'13d.png'},
	'shower sleet':{'id':612, 'icon':'13d.png'},
	'light rain and snow':{'id':615, 'icon':'13d.png'},
	'rain and snow':{'id':616, 'icon':'13d.png'},
	'light shower snow':{'id':620, 'icon':'13d.png'},
	'shower snow':{'id':621, 'icon':'13d.png'},
	'heavy shower snow':{'id':622, 'icon':'13d.png'},
	'mist':{'id':701, 'icon':'50d.png'},
	'smoke':{'id':711, 'icon':'50d.png'},
	'haze':{'id':721, 'icon':'50d.png'},
	'sand, dust whirls':{'id':731, 'icon':'50d.png'},
	'fog':{'id':741, 'icon':'50d.png'},
	'sand':{'id':751, 'icon':'50d.png'},
	'dust':{'id':761, 'icon':'50d.png'},
	'volcanic ash':{'id':762, 'icon':'50d.png'},
	'squalls':{'id':771, 'icon':'50d.png'},
	'tornado':{'id':781, 'icon':'50d.png'},
	'clear sky':{'id':800, 'icon':'01d.png'},
	'few clouds':{'id':801, 'icon':'02d.png'},
	'scattered clouds':{'id':802, 'icon':'03d.png'},
	'broken clouds':{'id':803, 'icon':'04d.png'},
	'overcast clouds':{'id':804, 'icon':'05d.png'},
	'tornado':{'id':900, 'icon':''},
	'tropical storm':{'id':901, 'icon':''},
	'hurricane':{'id':902, 'icon':''},
	'cold':{'id':903, 'icon':''},
	'hot':{'id':904, 'icon':''},
	'windy':{'id':905, 'icon':''},
	'hail':{'id':906, 'icon':''},
	'calm':{'id':951, 'icon':''},
	'light breeze':{'id':952, 'icon':''},
	'gentle breeze':{'id':953, 'icon':''},
	'moderate breeze':{'id':954, 'icon':''},
	'fresh breeze':{'id':955, 'icon':''},
	'strong breeze':{'id':956, 'icon':''},
	'high wind, near gale':{'id':957, 'icon':''},
	'gale':{'id':958, 'icon':''},
	'severe gale':{'id':959, 'icon':''},
	'storm':{'id':960, 'icon':''},
	'violent storm':{'id':961, 'icon':''},
	'hurricane':{'id':962, 'icon':''}
}
